let
    // Create a table with the current local datetimezone
    Source = #table(
        type table [Last Refreshed = datetimezone],
        {
            { DateTimeZone.LocalNow() }
        }
    ),

    // Optional: Change type with locale (not strictly necessary for datetimezone)
    #"Changed Type with Locale" = Table.TransformColumnTypes(
        Source,
        {{"Last Refreshed", type datetimezone}},
        "en-US"
    )
in
    #"Changed Type with Locale"


Then create DAX Measure: 
Last Refresh = CONCATENATE("Data Last Refreshed: ", MAX('Last Refresh'[Last Refreshed] ) )
